#!/usr/bin/env bash
# PreCompact hook: append a session checkpoint marker to CLAUDE.md before context compaction
# Full /preserve (AI-assisted) runs on demand; this hook leaves a breadcrumb so you know
# compaction happened and can run /preserve on resume.

set -uo pipefail

LOG_DIR="/Users/orginal/Library/CloudStorage/GoogleDrive-zachgladstone@gmail.com/My Drive/AI-Tools/logs/hooks"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/auto_preserve.log"

TS=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

# Walk up from PWD to find CLAUDE.md
find_claude_md() {
    local dir="$PWD"
    while [[ "$dir" != "/" ]]; do
        for name in "CLAUDE.md" "Claude.md" ".claude/CLAUDE.md"; do
            [[ -f "$dir/$name" ]] && echo "$dir/$name" && return 0
        done
        dir=$(dirname "$dir")
    done
    return 1
}

CLAUDE_MD=$(find_claude_md 2>/dev/null || true)

if [[ -n "$CLAUDE_MD" ]]; then
    printf '\n## Session Checkpoint (%s)\n\n' "$TS" >> "$CLAUDE_MD"
    printf '_Auto-generated by PreCompact hook. Run /preserve to add session learnings._\n\n' >> "$CLAUDE_MD"
    printf '[%s] PreCompact hook fired. Checkpoint appended to: %s\n' "$TS" "$CLAUDE_MD" >> "$LOG_FILE"
else
    printf '[%s] PreCompact hook fired. No CLAUDE.md found in path from: %s\n' "$TS" "$PWD" >> "$LOG_FILE"
fi

# Always exit 0 — never block compaction
exit 0
