"""
backtest_xgb_v9.py — Alpha158-Plus + OpenMythos 256-dim embedding XGBoost pipeline.

Feature stack (v8 + optional Mythos layer):
  - v8 base ~870+ features (v7 stack + Qlib Alpha158 + closeable-gaps)
  - [Optional] OpenMythos 256-dim embedding: per-(ticker, date) intraday embedding
    generated by scripts/mythos_features.py :: compute_mythos_embedding()

Total with Mythos: ~1126+ features. XGBoost handles this fine via scout-prune-refit.

Key differences from v8:
  1. build_v9_features() calls build_v8_features() then optionally adds Mythos layer.
  2. CLI flag --use-mythos-features (default: False).
  3. Mythos fallback: zero-vector if checkpoint missing/unset (never crashes).
  4. run_meta.json extended with use_mythos_features, mythos_checkpoint_path,
     mythos_feature_count, mythos_fallback_rows.
  5. pipeline_version / strategy_variant updated to v9.

Usage:
    # Without Mythos (identical to v8 behavior):
    python backtest_xgb_v9.py --ticker AAPL --output-dir /tmp/aapl_v9

    # With Mythos embedding features:
    python backtest_xgb_v9.py --ticker AAPL --output-dir /tmp/aapl_v9_mythos \\
        --use-mythos-features

    # With trained checkpoint:
    MYTHOS_CHECKPOINT_PATH=/path/to/mythos_financial_v0.pt \\
    python backtest_xgb_v9.py --ticker AAPL --output-dir /tmp/aapl_v9_real \\
        --use-mythos-features

DO NOT modify v8. This is a clean fork.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import warnings
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

WORK = Path(
    "/Users/orginal/Library/CloudStorage/"
    "GoogleDrive-zachgladstone@gmail.com/My Drive/"
    "AI-Tools/s&p500-ticker-mastery"
)
LABEL_EMBARGO_DAYS = 21

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Import v8 feature builder (non-destructive — v8.py is untouched)
# ---------------------------------------------------------------------------

from backtest_xgb_v8 import build_v8_features  # noqa: E402
from backtest_xgb_v7 import numeric_cols  # noqa: E402
import backtest_ml as bml  # noqa: E402
import xgboost as xgb  # noqa: E402

# Cross-sectional cache
try:
    import cross_sectional_features as csf
except Exception as _e:
    logger.warning("csf unavailable: %s", _e)
    csf = None

# ---------------------------------------------------------------------------
# Mythos integration
# ---------------------------------------------------------------------------

try:
    from mythos_features import (  # noqa: E402
        compute_mythos_embedding,
        get_feature_names as mythos_feature_names,
        MYTHOS_DISABLED,
    )
    MYTHOS_AVAILABLE = True
except Exception as _e:
    logger.warning(
        "[v9] mythos_features not importable: %s — will use zero-embedding fallback", _e
    )
    MYTHOS_AVAILABLE = False
    # Default-disabled when module missing — matches the 2026-05-21 OC-audit-drop posture.
    MYTHOS_DISABLED = True  # type: ignore[assignment]

    def compute_mythos_embedding(ticker: str, end_date: str) -> np.ndarray:  # type: ignore[misc]
        """Stub fallback when mythos_features.py cannot be imported."""
        return np.zeros(0, dtype=np.float32)

    def mythos_feature_names() -> list[str]:  # type: ignore[misc]
        return []


# Static cardinality kept for legacy run_meta.json metadata; ACTIVE count is
# len(MYTHOS_FEAT_NAMES) which is 0 when MYTHOS_DISABLED=1 (default 2026-05-21).
MYTHOS_FEATURE_DIM = 256
MYTHOS_FEAT_NAMES: list[str] = mythos_feature_names()


# ---------------------------------------------------------------------------
# Mythos embedding matrix builder
# ---------------------------------------------------------------------------


def _build_mythos_matrix(
    df: pd.DataFrame,
    ticker: str,
    *,
    log_interval: int = 100,
) -> tuple[pd.DataFrame, int]:
    """Compute per-row Mythos embeddings and return as a DataFrame.

    For each date in ``df.index``, calls ``compute_mythos_embedding(ticker, date)``.
    The function is already cache-aware (disk cache in /tmp/mythos_emb_cache/).

    Fallback: rows where the embedding is all-zeros are counted and logged.
    Zero embeddings add NO signal to XGBoost — they are safe but inert.

    Args:
        df: Feature DataFrame with DatetimeIndex (trading dates).
        ticker: Stock symbol used for cache/parquet lookup.
        log_interval: Log a progress line every N rows.

    Returns:
        Tuple of:
          - pd.DataFrame shape (N, 256) with MYTHOS_FEAT_NAMES columns,
            index matching df.index.
          - int count of rows that fell back to zeros.
    """
    n = len(df)
    emb_matrix = np.zeros((n, MYTHOS_FEATURE_DIM), dtype=np.float32)
    fallback_count = 0

    for i, ts in enumerate(df.index):
        date_str = pd.Timestamp(ts).strftime("%Y-%m-%d")
        try:
            emb = compute_mythos_embedding(ticker, date_str)
        except Exception as exc:
            logger.warning(
                "[mythos] exception for (%s, %s): %s — using zeros", ticker, date_str, exc
            )
            emb = np.zeros(MYTHOS_FEATURE_DIM, dtype=np.float32)

        if not np.any(emb):
            fallback_count += 1

        emb_matrix[i] = emb

        if log_interval > 0 and (i + 1) % log_interval == 0:
            logger.info(
                "  [mythos] processed %d/%d rows (fallback_so_far=%d)",
                i + 1,
                n,
                fallback_count,
            )

    mythos_df = pd.DataFrame(emb_matrix, index=df.index, columns=MYTHOS_FEAT_NAMES)
    return mythos_df, fallback_count


# ---------------------------------------------------------------------------
# v9 feature builder
# ---------------------------------------------------------------------------


def build_v9_features(
    ticker: str,
    universe_agg: Optional[dict] = None,
    use_mythos: bool = False,
) -> tuple[pd.DataFrame, int]:
    """Build v9 feature set: full v8 stack + optional OpenMythos 256-dim layer.

    Args:
        ticker: Stock symbol.
        universe_agg: Cross-sectional precomputed aggregates dict (from csf).
        use_mythos: If True, append 256 Mythos embedding features.

    Returns:
        Tuple of:
          - pd.DataFrame with all features + target column 'y'.
          - int fallback_rows (only meaningful when use_mythos=True;
            rows where Mythos returned zeros).
    """
    # Full v8 stack (unmodified)
    f = build_v8_features(ticker, universe_agg)
    logger.info("  [v9] after v8 stack: %d cols", f.shape[1])

    fallback_rows = 0

    # 2026-05-21 (OC audit rank #2): when MYTHOS_DISABLED (default), the
    # 256-col concat is SKIPPED regardless of the use_mythos flag. The flag is
    # preserved so legacy callers (CLI --use-mythos-features, retrain dispatch)
    # don't break; they simply become no-ops while MYTHOS_DISABLED=1.
    if use_mythos and not MYTHOS_DISABLED:
        logger.info("  [v9] computing Mythos embeddings for %d rows ...", len(f))
        checkpoint_path = os.environ.get(
            "MYTHOS_CHECKPOINT_PATH",
            str(
                Path(WORK).parent
                / "checkpoints"
                / "mythos_financial_v0.pt"
            ),
        )
        if not Path(checkpoint_path).exists():
            logger.warning(
                "  [v9] MYTHOS_CHECKPOINT_PATH not found (%s) — "
                "embeddings will be zero vectors (no signal added pre-training)",
                checkpoint_path,
            )

        mythos_df, fallback_rows = _build_mythos_matrix(f, ticker)

        before = f.shape[1]
        f = pd.concat([f, mythos_df], axis=1)
        added = f.shape[1] - before
        logger.info(
            "  [v9] +mythos embeddings: +%d cols -> %d total "
            "(fallback_rows=%d / %d)",
            added,
            f.shape[1],
            fallback_rows,
            len(f),
        )
    elif use_mythos and MYTHOS_DISABLED:
        logger.info(
            "  [v9] use_mythos=True but MYTHOS_DISABLED=1 (OC audit 2026-05-21 drop) — "
            "skipping 256-col concat; 0 cols added."
        )

    # Deduplicate columns (safety guard; Mythos names are unique by design)
    f = f.loc[:, ~f.columns.duplicated()]
    f = f.dropna(subset=["rsi_14", "atr_14", "ema_200", "fwd_ret_21d", "y"])
    return f, fallback_rows


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    ap = argparse.ArgumentParser(
        description="XGBoost v9 — v8 stack + optional OpenMythos 256-dim embeddings"
    )
    ap.add_argument("--ticker", required=True, help="Stock symbol e.g. AAPL")
    ap.add_argument("--output-dir", required=True, help="Directory for output files")
    ap.add_argument(
        "--use-mythos-features",
        action="store_true",
        default=False,
        help=(
            "DEPRECATED 2026-05-21 (OC audit rank #2 — Mythos dropped). When "
            "MYTHOS_DISABLED=1 (default) this flag is a no-op; the 256-col "
            "concat is skipped. Pass MYTHOS_DISABLED=0 in env to re-enable."
        ),
    )
    ap.add_argument("--prob-threshold", type=float, default=0.50)
    ap.add_argument("--sweep-threshold", action="store_true")
    ap.add_argument("--top-k", type=int, default=50)
    ap.add_argument("--tp-atr", type=float, default=1.5)
    ap.add_argument("--sl-atr", type=float, default=1.0)
    ap.add_argument("--max-hold", type=int, default=21)
    ap.add_argument("--strategy", default="default", help="Strategy label for metadata")
    args = ap.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # ---- Cross-sectional cache ----
    universe_agg = None
    cache_path = WORK / "cache" / "universe_agg_manifest.json"
    if cache_path.exists() and csf is not None:
        try:
            universe_agg = csf.precompute_universe_aggregates()
        except Exception as e:
            logger.warning("  [csf] cache load failed: %s", e)

    # ---- Build feature set ----
    f, mythos_fallback_rows = build_v9_features(
        args.ticker,
        universe_agg,
        use_mythos=args.use_mythos_features,
    )
    fc = numeric_cols(f)
    logger.info(
        "  TOTAL features: %d; rows: %d; mythos_fallback_rows: %d",
        len(fc),
        len(f),
        mythos_fallback_rows,
    )

    # Resolve checkpoint path for metadata
    mythos_checkpoint_path = os.environ.get("MYTHOS_CHECKPOINT_PATH", "")
    if not mythos_checkpoint_path:
        mythos_checkpoint_path = str(
            Path(WORK).parent / "checkpoints" / "mythos_financial_v0.pt"
        )

    # ---- Walk-forward folds ----
    folds = bml.make_walk_forward_folds(f, train_months=24, test_months=12, step_months=12)
    logger.info("  folds: %d", len(folds))
    all_probs = pd.Series(np.nan, index=f.index)
    fold_summaries = []
    fold_top_features = []
    fold_mythos_importances = []  # track Mythos-specific feature importances

    mythos_feat_set = set(MYTHOS_FEAT_NAMES)

    for fold in folds:
        train_end_emb = (
            pd.Timestamp(fold["train_end"])
            - pd.tseries.offsets.BDay(LABEL_EMBARGO_DAYS)
        )
        train = f[
            (f.index >= fold["train_start"]) & (f.index < train_end_emb)
        ]
        oos = f[
            (f.index >= fold["oos_start"]) & (f.index < fold["oos_end"])
        ]
        if len(train) < 50 or len(oos) < 20:
            continue

        # Scout model — get top-K features by gain
        X_tr_all = train[fc].fillna(0).values
        y_tr = train["y"].values
        X_oos_all = oos[fc].fillna(0).values

        scout = xgb.XGBClassifier(
            max_depth=3,
            learning_rate=0.05,
            n_estimators=50,
            tree_method="hist",
            eval_metric="logloss",
            n_jobs=1,
            random_state=42,
            verbosity=0,
        )
        scout.fit(X_tr_all, y_tr)

        importances = list(zip(fc, scout.feature_importances_))
        importances.sort(key=lambda x: -x[1])
        top_features = [c for c, imp in importances[: args.top_k] if imp > 0]
        if len(top_features) < 10:
            top_features = [c for c, _ in importances[: args.top_k]]
        fold_top_features.append({"fold": fold["fold"], "top_features": top_features[:30]})

        # Track Mythos feature importances specifically
        imp_dict = dict(importances)
        mythos_imps = {
            feat: float(imp_dict.get(feat, 0.0))
            for feat in MYTHOS_FEAT_NAMES
            if feat in fc and imp_dict.get(feat, 0.0) > 0
        }
        top_mythos = sorted(mythos_imps.items(), key=lambda x: -x[1])[:10]
        fold_mythos_importances.append(
            {
                "fold": fold["fold"],
                "mythos_in_top50": sum(
                    1 for feat in top_features if feat in mythos_feat_set
                ),
                "top_mythos": dict(top_mythos),
            }
        )

        # Final model on pruned features
        X_tr = train[top_features].fillna(0).values
        X_oos = oos[top_features].fillna(0).values
        final = xgb.XGBClassifier(
            max_depth=4,
            learning_rate=0.05,
            n_estimators=100,
            tree_method="hist",
            eval_metric="logloss",
            n_jobs=1,
            random_state=42,
            verbosity=0,
        )
        final.fit(X_tr, y_tr)
        probs = final.predict_proba(X_oos)[:, 1]
        all_probs.loc[oos.index] = probs
        fold_summaries.append(
            {
                "fold": fold["fold"],
                "n_train": len(train),
                "n_oos": len(oos),
                "n_top_features": len(top_features),
                "mean_oos_prob": float(probs.mean()),
            }
        )

    # ---- Threshold sweep or fixed ----
    sdf = None
    if args.sweep_threshold:
        rows = []
        for thr in np.arange(0.46, 0.70, 0.02):
            sig = all_probs > thr
            trades = bml.simulate(
                f, sig.fillna(False), args.tp_atr, args.sl_atr, args.max_hold
            )
            mm = bml.compute_metrics(trades)
            rows.append({"thr": round(thr, 2), **mm})
        sdf = pd.DataFrame(rows)
        sdf.to_csv(f"{args.output_dir}/threshold_sweep.csv", index=False)
        mask = (
            (sdf["profit_factor"] >= 1.5)
            & (sdf["win_rate"] >= 0.53)
            & (sdf["n_trades"] >= 8)
            & (sdf["max_drawdown_pct"] >= -0.03)
            & (sdf["total_return_pct"] > 0)
        )
        if mask.any():
            chosen_thr = float(
                sdf[mask]
                .sort_values("profit_factor", ascending=False)
                .iloc[0]["thr"]
            )
        else:
            chosen_thr = float(
                sdf.sort_values("profit_factor", ascending=False).iloc[0]["thr"]
            )
        logger.info("  -> chose thr=%.2f", chosen_thr)
    else:
        chosen_thr = args.prob_threshold

    # ---- Final simulation ----
    final_sig = (all_probs > chosen_thr).fillna(False)
    trades = bml.simulate(f, final_sig, args.tp_atr, args.sl_atr, args.max_hold)
    metrics = bml.compute_metrics(trades)
    logger.info(
        "  FINAL thr=%.2f: n=%d, WR=%.3f, PF=%.3f, RET=%.4f, DD=%.4f",
        chosen_thr,
        metrics["n_trades"],
        metrics.get("win_rate", 0),
        metrics.get("profit_factor", 0),
        metrics.get("total_return_pct", 0),
        metrics.get("max_drawdown_pct", 0),
    )

    trades.to_csv(f"{args.output_dir}/trades.csv", index=False)
    if sdf is not None:
        sdf.to_csv(f"{args.output_dir}/threshold_sweep.csv", index=False)

    # ---- Serialization helper ----
    def to_py(obj):
        if isinstance(obj, dict):
            return {k: to_py(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [to_py(v) for v in obj]
        if hasattr(obj, "item"):
            return obj.item()
        if isinstance(obj, float) and (np.isnan(obj) or np.isinf(obj)):
            return None
        return obj

    # ---- run_meta.json ----
    meta = to_py(
        {
            "ticker": args.ticker,
            "pipeline_version": "xgb_v9_mythos",
            "strategy_variant": "ML_XGB_v9_mythos",
            "strategy": args.strategy,
            "run_at": datetime.utcnow().isoformat() + "Z",
            "features_total": len(fc),
            "top_k": args.top_k,
            "rows": len(f),
            # Mythos-specific metadata
            "use_mythos_features": args.use_mythos_features,
            "mythos_checkpoint_path": mythos_checkpoint_path,
            "mythos_feature_count": MYTHOS_FEATURE_DIM if args.use_mythos_features else 0,
            "mythos_available": MYTHOS_AVAILABLE,
            "mythos_fallback_rows": mythos_fallback_rows,
            "mythos_fallback_pct": (
                round(mythos_fallback_rows / max(len(f), 1), 4)
                if args.use_mythos_features
                else None
            ),
            "feature_sources": {
                "base+intraday+alt+insight_v3+parts1-4": "~587",
                "cross_sectional": "17 (if cache)",
                "macro_yfinance": "40",
                "strategy_signal+five_filter": "~25",
                "google_trends": "7",
                "insider_form4": "8",
                "multi_timeframe_h1_h4_m5_m15": "15 (v7)",
                "news_sentiment_vader": "8 (v7)",
                "vol_estimators": "14 (v7)",
                "qlib_alpha158_pandas_port": "158 (v8)",
                "closeable_gaps_yfinance_finra": "18 (v8 patch)",
                "openmythos_256dim_embedding": (
                    "256 (v9 NEW)" if args.use_mythos_features else "disabled"
                ),
            },
            "walk_forward_folds": len(fold_summaries),
            "strategy_params": {
                "name": "ML_XGB_v9_mythos",
                "side": "long",
                "tp_atr": args.tp_atr,
                "sl_atr": args.sl_atr,
                "max_hold_days": args.max_hold,
                "prob_threshold": chosen_thr,
                "threshold_swept": args.sweep_threshold,
                "model": "XGBClassifier (scout-prune-refit top-K)",
                "slippage_bps": 5.0,
                "fee_per_share": 0.0035,
                "notional_per_trade": 5000,
            },
            "metrics_oos_aggregate": metrics,
            "fold_summaries": fold_summaries,
            "fold_top_features": fold_top_features,
            "fold_mythos_importances": fold_mythos_importances,
        }
    )

    meta_path = f"{args.output_dir}/run_meta.json"
    with open(meta_path, "w") as fp:
        json.dump(meta, fp, indent=2, default=str)
    logger.info("  Wrote %s", meta_path)


if __name__ == "__main__":
    main()
