"""gabriel_alpaca_timeframes_30m dir-glob loader (template-generated, dir_glob tier)

Auto-generated by feature_wiring_consumer_daemon dir-glob tier.
Feature: gabriel_alpaca_timeframes_30m
Canonical path: /Users/orginal/Library/CloudStorage/GoogleDrive-zachgladstone@gmail.com/My Drive/version_3 - Gabriel/Gabriel_Alpaca TimeFrames/Minutes TimeFrames/30Min/
Path pattern: /sessions/vigilant-festive-dirac/mnt/My Drive/version_3 - Gabriel/Gabriel_Alpaca TimeFrames/Minutes TimeFrames/30Min/**
Approx file count (audit): 30297
Rationale: OHLCV bars 30min
Generated: 2026-05-18T04:33:48.155572+00:00

NO-LOOKAHEAD AUDIT:
  - This wrapper only READS parquet/csv files; it does not synthesize forward-
    looking features. Any feature derived from the returned DataFrame must
    .shift(1) same-bar columns before training/eval — that responsibility
    sits with the downstream feature module that consumes this loader.
  - Empty/missing data returns an empty DataFrame (never raises).
  - Ticker filter is applied at the path level (per-ticker subdirectory) AND
    by column when the parquet has a ticker column.
"""
from __future__ import annotations

import glob
import os
from pathlib import Path
from typing import Optional

try:
    import pandas as pd
except ImportError:  # noqa: BLE001 — pipeline-callable wrapper must not raise
    pd = None  # type: ignore[assignment]


# Canonical path resolved at module load. Path is Mac-side; do NOT prefix with
# /sessions/... mount — the consumer normalizes mirror prefixes upstream.
_CANONICAL_PATH = '/Users/orginal/Library/CloudStorage/GoogleDrive-zachgladstone@gmail.com/My Drive/version_3 - Gabriel/Gabriel_Alpaca TimeFrames/Minutes TimeFrames/30Min/'
_PATH_PATTERN = '/sessions/vigilant-festive-dirac/mnt/My Drive/version_3 - Gabriel/Gabriel_Alpaca TimeFrames/Minutes TimeFrames/30Min/**'


def _candidate_globs(ticker: Optional[str] = None) -> list[str]:
    """Return the list of glob patterns to try for `ticker`.

    Many of these directories are organized per-ticker (``<dir>/<TICKER>/*.parquet``)
    while a few are merged-per-ticker (``<dir>/<TICKER>.parquet``). We try both.
    """
    root = _CANONICAL_PATH.rstrip("/")
    if ticker:
        return [
            f"{root}/{ticker}/*.parquet",
            f"{root}/{ticker}.parquet",
            f"{root}/**/{ticker}/*.parquet",
            f"{root}/**/{ticker}.parquet",
            # Less-common: csv / json variants
            f"{root}/{ticker}/*.csv",
            f"{root}/{ticker}.csv",
            f"{root}/{ticker}/*.json",
        ]
    # No ticker filter: pull a small sample (first-found parquet).
    return [
        f"{root}/*.parquet",
        f"{root}/**/*.parquet",
    ]


def _read_one(path: str):  # -> Optional[pd.DataFrame]
    if pd is None:
        return None
    try:
        if path.endswith(".parquet"):
            return pd.read_parquet(path)
        if path.endswith(".csv"):
            return pd.read_csv(path)
        if path.endswith(".json"):
            return pd.read_json(path)
    except Exception:  # noqa: BLE001
        return None
    return None


def compute_gabriel_alpaca_timeframes_30m_features(
    ticker: Optional[str] = None,
    start: Optional[str] = None,
    end: Optional[str] = None,
):  # -> pd.DataFrame
    """Load + concatenate all files in the directory glob matching ticker.

    Args:
        ticker: Optional ticker symbol (e.g. ``"AAPL"``). When provided we
            restrict the glob to per-ticker subdirectories first.
        start: Optional ISO date filter (e.g. ``"2021-01-01"``); applied to
            the index when the returned frame has a datetime index OR a ``ts``
            column.
        end: Optional ISO date filter (exclusive upper bound).

    Returns:
        pandas.DataFrame indexed by ts (if available), concatenated across all
        matched files. Empty DataFrame on no-match / pandas-missing /
        unreadable-dir. NEVER raises — graceful zero-fill semantics.
    """
    if pd is None:
        return None  # pandas not installed; caller must handle None
    frames = []
    seen_files: set[str] = set()
    for pat in _candidate_globs(ticker):
        for fp in glob.glob(pat, recursive=True):
            if fp in seen_files:
                continue
            seen_files.add(fp)
            df = _read_one(fp)
            if df is None or df.empty:
                continue
            # Apply ticker column filter when available
            if ticker and "ticker" in df.columns:
                df = df[df["ticker"] == ticker]
            if ticker and "symbol" in df.columns:
                df = df[df["symbol"] == ticker]
            frames.append(df)
            # Safety cap: don't slurp 30k files into memory in one call.
            if len(frames) >= 64:
                break
        if len(frames) >= 64:
            break

    if not frames:
        return pd.DataFrame()

    try:
        out = pd.concat(frames, ignore_index=False, sort=False)
    except Exception:  # noqa: BLE001
        # Mixed-schema fallback: align on union of columns
        try:
            cols = sorted({c for f in frames for c in f.columns})
            normalized = [f.reindex(columns=cols) for f in frames]
            out = pd.concat(normalized, ignore_index=False, sort=False)
        except Exception:  # noqa: BLE001
            return pd.DataFrame()

    # Date filter (best-effort; works on datetime index OR a `ts` column)
    if start is not None or end is not None:
        try:
            if "ts" in out.columns:
                ts = pd.to_datetime(out["ts"], errors="coerce")
                mask = pd.Series(True, index=out.index)
                if start is not None:
                    mask &= ts >= pd.Timestamp(start)
                if end is not None:
                    mask &= ts < pd.Timestamp(end)
                out = out[mask]
            elif isinstance(out.index, pd.DatetimeIndex):
                if start is not None:
                    out = out[out.index >= pd.Timestamp(start)]
                if end is not None:
                    out = out[out.index < pd.Timestamp(end)]
        except Exception:  # noqa: BLE001
            pass

    return out


# Public alias: many older pipelines expect a generic `load_features(ticker)`
# signature. Keep both for forward-compat.
load_features = compute_gabriel_alpaca_timeframes_30m_features
